pipeline:
  build:
    image: openjdk:8-alpine
    dns_search: interactive-instruments.de
    extra_hosts:
      - "project-management:192.168.230.8"
    commands:
      - git submodule update --init --recursive --remote
      - sed -i "s#https://gitlab.wetransform.to/hale/hale-build-support/raw/.*/updatesites/platform#file:$TRAVIS_BUILD_DIR/hale-platform/build/updatesite#" hale/platform/hale-platform.target
      - sed -i "s#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\".*\"/>#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\"0.0.0\"/>#" hale/platform/hale-platform.target
      - sed -i "s#repositories {#repositories {jcenter()#" hale-platform/build.gradle
      - cd hale-platform && ./gradlew --info updateSite