---
kind: pipeline
type: docker
name: default

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_update_remote: true
#    dns_search: interactive-instruments.de
#    extra_hosts:
#      - "project-management:192.168.230.8"

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - .gradle/caches
        - .gradle/wrapper

  - name: build
    image: openjdk:8-alpine
    commands:
      - export GRADLE_USER_HOME=$DRONE_WORKSPACE/.gradle
      - apk add --no-cache bash
#      - sed -i "s#https://gitlab.wetransform.to/hale/hale-build-support/raw/.*/updatesites/platform#file:$DRONE_WORKSPACE/hale-platform/build/updatesite#" hale/platform/hale-platform.target
#      - sed -i "s#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\".*\"/>#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\"0.0.0\"/>#" hale/platform/hale-platform.target
#      - sed -i "s#repositories {#repositories {\\nmaven { url 'https://repo.boundlessgeo.com/main/'}#" hale-platform/build.gradle
#      - echo "platform{eclipseMirror='http://dl.bintray.com/simon-scholz/eclipse-apps/eclipse-p2-minimal.tar.gz'}" >> hale-platform/build.gradle
#      - cd hale-platform && ./gradlew --info --stacktrace updateSite
#      - cd ..
#      - echo "export HALEVERSION=$(grep -oPm1 '(?<=version = .)[\w\.]+' $DRONE_WORKSPACE/hale/build/config.groovy).SNAPSHOT" > env.sh
#      - echo "export HALETAG=ii.20181214111318" >> env.sh
      - echo "export HALETAG=ii.$(date +'%Y%m%d%H%M%S')" >> env.sh
      - source env.sh
#      - cd hale 
#      - ./build.sh product --arch x86_64 --os linux --tag $HALETAG HALE
#      - ./build.sh product --arch x86_64 --os windows --tag $HALETAG HALE

  - name: publish
    image: cicd100:5000/iide/drone-download-link:latest
    pull: true
    settings:
      host: cicd100
      username: 
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      source: env.sh
      target: bla
      debug: true

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - .gradle/caches
        - .gradle/wrapper


volumes:
  - name: cache
    host: 
      path: /tmp/cache