language:
- java

python:
  - "3.5"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

# disable the default submodule logic
git:
  submodules: false

env:
  global: 
  - TERM=dumb
  - AWS_ACCESS_KEY_ID=AKIAI6J446H2Y5TC5QZA
  #- secure: "bAinRwtqzMmDw+5G4gaOQvkEk25umu7iQBLrbg4dd9gFbrWDUo8FTQJBopBqUfrQXqGoPYFzzHCQ16/ZBQBi9ZPknn19TslnpA7W8pbm3pIktpd40wXVujPhbtxRRt6un0iJxaIQ0qWKddGIuYtIkPr10+KLZGZFcRXRD94LFbBuqNCsT3Mar26hz27Ntb8NZxwT5beZLAoHFOOxk6qoifMDyJPyTw6o9vIDhvnOFXKV4qwRqYa5Ln1edSXGTpGNSupDs2n9tS0KRFZirkbaxmFNx2/dHh5X46iRFTI+wSKNA2ZM6CKSe0I+opHti9s0LqNqg2/xxL+OFfjzYWg08gfmf/jnnvyN+GyKvTPxB2T4fi+/WUJsgCCaa4QweBW2h1ZxJ7TJn0S7q1WSSWyEbwbI+HL73Vq8ddRZmY+34e8Thxls8jNd4VRGB04eoiSkMmJZHMF6kGsCIvypjFygujyxcAQrhPWYrOUbISUYMYOEqWDXc/JDyoOTm81kFFsAhNdAh/idD6pfL2nehYzXoi7+4Bs9ntCZrXdjHtDrCKGJaGy7fXl7xrv+VRp4SuMQrz5tG3iRM8rBRRNV1ytvI5113qcO13id8s5+q9hNiUU9p4rLoP5Qb1lr1koXZQwy5yd/L61BZnvbBm1Kg3bxvZWJkC5zmvPW+/FfL56Hx+o="
  - secure: "Ez3TZIXSgWuUgVhcDgjT8tn72MU20utypBQMT38zcWy4ncqOtK46m5eXNSpDsmsEYYcnQpYm8bh7H16QJ/iYmKPQpf6hrNIJXo4SwHG1p3Johr/HQrzBdzf44AgEBNAJ7O5UlMb6jXYl/JsLPs6QycnZhNsCqd7BRbgvrmL7y/sCBXVbGVd/Ze5e7oGcWa5akaPxtwT+OhYlCRfViYW+OKIOtOw2Vu1XUPv7pTAkk38A7AAmjfjZEZJ03pJtWUm2TyjOUFg0FOtIowe0OCfxWXpJcTQ+F2M+r1w+TGc3aNpdIlIIwrgjyYVBNWcycArqyW4lqRBZx1dMY0u+Fuw4VEOGJQbvb4pEPrnQzM2AGzJtA/fLEzofoldJ9sGbVdkEotBDOenpHk/Fqkad6zjLHNMHAnKpi97mKW3Eqzciw+qovpXCo7KH9xXeEBj0wy38IhFtMIrFTPE/wWCa6V9C2sKgygwnPO5fkuMH6oaeToqWuGiqMhVrdhtUDn3YL2kOQ/bv4DXOuGpaQK9TSEP6FRAIC6AzT+Vv4+7lBLxoZ9ONiYzoTvSQsb60Mp/XpjfeEqsAkh4K7EaVxENBzAfDkxLP3UBaA0fzkrREylBi4Gte6/pd4552Y4N3iOpYZO86LVYaSAw9p9sqyvqyoM91Syaka1rAjxDdF5n/M0qTU80="

# get current remote HEAD of submodules
# adjust hale to use local platform
before_install:
  - git submodule update --init --recursive --remote
  - sed -i "s#https://gitlab.wetransform.to/hale/hale-build-support/raw/.*/updatesites/platform#file:$TRAVIS_BUILD_DIR/hale-platform/build/updatesite#" hale/platform/hale-platform.target
  - sed -i "s#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\".*\"/>#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\"0.0.0\"/>#" hale/platform/hale-platform.target
  - sed -i "s#repositories {#repositories {\\nmaven { url 'https://repo.boundlessgeo.com/main/'}#" hale-platform/build.gradle
  - echo "platform{eclipseMirror='http://dl.bintray.com/simon-scholz/eclipse-apps/eclipse-p2-minimal.tar.gz'}" >> hale-platform/build.gradle

# build updatesite  
#install:
#- cd hale-platform && ./gradlew --info --stacktrace updateSite

# build hale
script:
- echo "export HALEVERSION=$(grep -oPm1 '(?<=version = .)[\w\.]+' $TRAVIS_BUILD_DIR/hale/build/config.groovy).SNAPSHOT" > env.sh
- echo "export HALETAG=ii.20181214111318" >> env.sh
#- echo "export HALETAG=ii.$(date +'%Y%m%d%H%M%S')" >> env.sh
- source env.sh
#- cd ../hale 
#- ./build.sh product --arch x86_64 --os linux --tag $HALETAG HALE
#- ./build.sh product --arch x86_64 --os windows --tag $HALETAG HALE
#
#deploy:
#  provider: s3
#  region: eu-central-1
#  bucket: "ii.hale.dev"
#  access_key_id: "$AWS_ACCESS_KEY_ID"
#  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
#  local_dir: "$TRAVIS_BUILD_DIR/hale/build/target"
#  skip_cleanup: true
#
#after_deploy:
- pip install --user awscli
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set default.region eu-central-1
- aws s3 presign s3://ii.hale.dev/hale-studio-$HALEVERSION-$HALETAG-linux.gtk.x86_64.tar.gz --expires-in 604800
- aws s3 presign s3://ii.hale.dev/hale-studio-$HALEVERSION-$HALETAG-win32.win32.x86_64.zip --expires-in 604800

