language:
- java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

# disable the default submodule logic
git:
  submodules: false

env:
  global: 
  - TERM=dumb
  - secure: ak9e6zXseOVS5V+NdPIcyWJMCZfrUg50cAKsCCrPFVBTXXnSk7DSPCAjfiW9oEu9buSHpeHUu9MItu4NfN9i1SA17xvq0pNO/VC9e4WpsjA3rHGLXfPtjEcX9ieLhQjEVtdjlSlY4ZeGkWcbKQW0bwRASojAe0RnyTv1BykVNfmWRDZMysp8JEPePt08Pw2XTtFVBH703dbL9fNNoRGDEbs5tBZ8e9yP6wksXeU0Ha881Xy3sRdvGViRVxK41my1P8WTFmYv2GgdaNgQ8tBF5snsU/4D58JNs/5UsI2bAbUcfFnJC2ry/X5vbb4M/NpqYcWCP8GTHd20PCLM+dpX+9CEB2svRnnXRjHPR7UOO88aPedipPkVD3e56yCyv04IykTLB9LUxPc9PFBRkKfY3OK/Lhp/SFx2jaLZJpplXsxqB9Q0hWsiXaroaUj0yb0pd3m7sjVPR7NisWmyRIA72Zua4EEJHBR66N4po2y2WCVgT3FhkXoGZGaCczlzA8h6nvBlNbHO+na3kQ1lV1ADNjXcf8dWwgkzhkzfYQzBVMO6M5R46NgpRRe/yT6KZF3Y77DLUYrKOZC7uA1ywulT75v4mNRkGxJAbmOWJ98qikMyln8TVBq7Ujq7iSAadwJRMggT24Y/dX3V9swuloqPy31pTPRNYeh8IPvsrDUUhbc=
  - secure: mbhSFZkeBoKQ0mzGad/euk95uUwIiM4L4AN8LBZVUYT2Wgmy251CqdV/0LBiMlafMGDBc3lAj1HHFhrx+9aO5rD53xYhflX47qjgIFS8u/C3m8C+BiX57IChtNFMBbpz+UknYK261mHU4u2yuOcrVDsqdwMn2VxLWaZSdmWU6ddLYXKGwglaSWeHzhiE7fufG6xiZfT+UpRiHAf4TsjFskAczv0HgoUe8nUaIMFseqpqchEzthzdbcnL78CyHmmnuikq8KhHIBad9kC0MGuIv71UFmbin5OvywsYHU9xGvmssSzPCNl0BEFEKZ8Wn/Mhk8lg6hAVeCQy1sV9f3MmDaOkrNGENQXQfOE3Kt5/YNHqmoGG7YruAOHWgMlo/uiNGnFcwnON/0G7SHCDQXXJj8O8gXys/FzfXIx8tG7IFHrJy3mQc10CX1AIoPiI7ubCNK1UKScirC5NsTuML8e1z3YYP+6j12CxluAeWfZmXJW/nH1tq+n0cAxK7s2xC1wxL1avT1xFKSsX7r4a+MeojuYrXa/o1wvqVgOq5nvZ7fay7ha6DaE2t3k5KyNWB6PC7ow0OLQZm4r32cgSXW+t1yOkFk2e5r0qJgWzIxULnYK4nYOFz4cs2YuJbpoZFLE9iSd5LSQdG/UrmxEKMZMHVH8mAyKMYQ6OStAIll7SpFk=

# get current remote HEAD of submodules
# adjust hale to use local platform
before_install:
  - git submodule update --init --recursive --remote
  - sed -i "s#https://gitlab.wetransform.to/hale/hale-build-support/raw/.*/updatesites/platform#file:$TRAVIS_BUILD_DIR/hale-platform/build/updatesite#" hale/platform/hale-platform.target
  - sed -i "s#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\".*\"/>#<unit id=\"eu.esdihumboldt.hale.platform.feature.group\" version=\"0.0.0\"/>#" hale/platform/hale-platform.target
  - sed -i "s#repositories {#repositories {\\nmaven { url 'https://repo.boundlessgeo.com/main/'}#" hale-platform/build.gradle
  - echo "platform{eclipseMirror='http://dl.bintray.com/simon-scholz/eclipse-apps/eclipse-p2-minimal.tar.gz'}" >> hale-platform/build.gradle

# build updatesite  
install:
- cd hale-platform && ./gradlew --info --stacktrace updateSite

# build hale
script:
- cd ../hale && ./build.sh product --arch x86_64 --os linux HALE

deploy:
  provider: bintray
  file: "$TRAVIS_BUILD_DIR/.bintray.json"
  user: "$BINTRAY_USER"
  key: "$BINTRAY_KEY"
  skip_cleanup: true
